android.nonTransitiveRClass=false

kotlin.code.style=official

# Configuration should be synced with [/gradle/build-logic/gradle.properties]
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.parallel=true

# 开启 Configuration Cache（日志中推荐开启）
org.gradle.configuration-cache=true

# 增大 Gradle 守护进程内存（建议分配 8G~12G，CPU 性能强劲时大内存能大幅提升 Kotlin 编译器速度）
org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8 -XX:+UseG1GC

# 开启 Kotlin 增量编译
kotlin.incremental=true